### PR TITLE
Feature: dynamic partials

### LINKED ISSUE #34: Dynamic partials
Not implemented: [dynamic partials](http://handlebarsjs.com/partials.html#dynamic-partials)

### PR DESCRIPTION
**Pull request by maxkoryukov**
Implementation for [dynamic partials](http://handlebarsjs.com/partials.html#dynamic-partials)

Fix #34

### CODE REVIEW

**Comment by maxkoryukov** [comment]
@wbond is there a chance to merge?

**Comment by wbond** [comment]
Unfortunately I am currently way overcommitted and semi burnt out, so I'm not sure when I would get to this.

I gave @isaacd push access a while ago. He may be able to review at some point.

**Comment by maxkoryukov** [comment]
@wbond, off-topic question: in #8 you told, that you want to rewrite lib. As I understood this won't happen, and makes sense to improve exactly this lib

**Comment by wbond** [comment]
@maxkoryukov Yes, I don't foresee having the time to rewrite this, and even if I did, I don't think it would end up being a wise choice based on other priorities in life. Sorry!

**Comment by maxkoryukov** [comment]
Ping @isaacd

**Comment by maxkoryukov** [comment]
@wbond , be careful: there are **two** guys: @isaacdd and @isaacd . First has committed something to this repo, the second has no relation to the project;)

**Comment by maxkoryukov** [comment]
ping @isaacdd

**Comment by isaacdd** [comment]
@maxkoryukov thanks! I will take a look soon.

**Comment by maxkoryukov** [comment]
And I got the first build;)

selection_011

**Comment by maxkoryukov** [comment]
@isaacdd , done.

I have added two tests from handlebars.js. Now we are in sync with JS version (at least, on this chunk of code)
Other test in JS-version are written for other partials' stuff, so I've skipped them.

Also, I have added another one test, so, finally there are tests for:

* dynamic partial call
* dynamic partial name taken:
  * from literal argument
  * from context
* dynamic partial with explicit scope

**Comment by maxkoryukov** [comment]
there are a lot of `flake8` commits. It is because my local branch is not flake8-ready, and I couldn't run `flake8` locally (now it gives ton of errors). Don't turn it off, after merging every developer will be able to run flake8 locally, and fix errors before sending a PR

**Comment by isaacdd** [comment]
@maxkoryukov I tried to introduce flake8 but stopped after seeing lots of errors. If it is a lot of work, we can turn it off and do the clean up in a separate PR.

**Comment by maxkoryukov** [comment]
@isaacdd with existing settings (see [`setup.cfg`](https://github.com/wbond/pybars3/pull/37/files#diff-380c6a8ebbbce17d55d50ef17d3cf906) in already merged #37) current codebase passes all checks (proofs are on [travis CI, in my repo](https://travis-ci.org/maxkoryukov/pybars3/builds/181715165) )

**Comment by IsaacD** [comment]
Whats going on? sorry I have been super busy and havent been following.
Someone feel free to email me at isaacdttn@gmail.com and let me know whats
going \on ill help anyway I can

**Comment by maxkoryukov** [comment]
HEllo! Any news on this?
ping @isaacdd

**Pull request merged**
